#db.type: mysql
#db.host: localhost
#db.port: 3306
#db.database: telivery
#db.timezone: Asia/Seoul
#
#
#spring:
#  datasource:
#    tomcat:
#      jmx-enabled: true
#  application:
#    name: api
#    debug: true
#
#spring.datasource:
#    username: root
#    password: asdfasdf
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:${db.type}://${db.host}:${db.port}/${db.database}?serverTimezone=${db.timezone}&characterEncoding=UTF-8
#
#spring.jpa:
#  database: mysql
#  show-sql: false
#  properties.hibernate.format_sql: true
#  hibernate:
#    dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#    ddl-auto: update


server:
  port: 8000